#!/usr/bin/python3
import irctestframework.irctest

# Because services are only tested on Windows,
# the account extban needed to be placed here.

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, skip = c3a, creator=c1a)
m.expect(c1a, "users in channel", "JOIN")
m.clearlog()
print

m.send(c1a, "MODE " + chan + " +iI ~a:*")
m.expect(c1a, "expect ban to be set", ":.+ MODE " + chan + " \+iI")
m.clearlog()
print

m.send(c3a, "JOIN " + chan)
m.expect(c3a, "Client should receive error on JOIN attempt", ":irc.+ 473 $c3a " + chan + " :Cannot join channel \(\+i\)")
m.not_expect_all("Client should NOT be able to join with +b ~a:* when not logged in", ":c3a.* JOIN ")
m.clearlog()
print

m.send(c1a, "MODE " + chan + " -I+I ~a:* ~a:client3")
m.expect(c1a, "expect ban to be set", ":.+ MODE " + chan + " -I\+I")
m.clearlog()
print

m.send(c3a, "JOIN " + chan)
m.expect(c3a, "Client should receive error on JOIN attempt", ":irc.+ 473 $c3a " + chan + " :Cannot join channel \(\+i\)")
m.not_expect_all("Client should NOT be able to join with +b ~a:client3 when not logged in", ":c3a.* JOIN ")
m.clearlog()
print

m.send(c3a, "NS IDENTIFY client3 test")
m.expect(c3a, "Identified to account", ":irc.* 900 ", timeout = 10)
m.clearlog()
print

m.send(c3a, "JOIN " + chan)
m.not_expect(c3a, "Client should NOT receive error on JOIN attempt", ":irc.+ 473")
m.expect_all("Client should be able to join now that it is logged in", ":c3a.* JOIN ")
m.clearlog()
print

m.send(c3a, "PART " + chan)
m.send(c1a, "MODE " + chan + " -I+I ~a:client3 ~a:0")
m.expect(c1a, "expect ban to be set", ":.+ MODE " + chan + " -I\+I")
print

m.send(c3a, "JOIN " + chan)
m.expect(c3a, "Client should receive error on JOIN attempt", ":irc.+ 473 $c3a " + chan + " :Cannot join channel \(\+i\)")
m.not_expect_all("Client should NOT be able to join with +b ~a:0 when logged in", ":c3a.* JOIN ")
m.clearlog()
print

m.send(c3a, "NS LOGOUT")
m.send(c3a, "PART " + chan)
m.expect(c3a, "NS LOGOUT succesful", "been logged out", timeout=10)
m.clearlog()
print

m.send(c3a, "JOIN " + chan)
m.not_expect(c3a, "Client should NOT receive error on JOIN attempt", ":irc.+ 473")
m.expect_all("Client should be able to join now when logged out and with +I ~a:0", ":c3a.* JOIN ")
m.clearlog()
print
