#!/usr/bin/python
import irctestframework.irctest

# Because services are only tested on Windows,
# the account extban needed to be placed here.

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, skip = c3a, creator=c1a)
m.expect(c1a, "users in channel", "JOIN")
m.clearlog()
print

m.send(c3a, "SETNAME bannedrealname")
m.send(c1a, "MODE " + chan + " +iI ~a:client3")
m.expect(c1a, "expect ban to be set", ":.+ MODE " + chan + " \+iI")
m.clearlog()
print

m.send(c3a, "JOIN " + chan)
m.expect(c3a, "Client should receive error on JOIN attempt", ":irc.+ 473 $c3a " + chan + " :Cannot join channel \(\+i\)")
m.not_expect_all("Client should NOT be able to join with +b ~r", ":c3a.* JOIN ")
m.clearlog()
print

m.send(c3a, "NS IDENTIFY client3 test")
m.expect(c3a, "something", "(you are now recognized|You are now identified)", timeout = 5)
m.clearlog()
print

m.send(c3a, "JOIN " + chan)
m.not_expect(c3a, "Client should NOT receive error on JOIN attempt", ":irc.+ 473")
m.expect_all("Client should be able to join now", ":c3a.* JOIN ")
m.clearlog()
print
