#!/usr/bin/python
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send(c1a, "IDENTIFY client1 test")
m.expect(c1a, "Identified message", "You are now identified", timeout = 10)
m.clearlog()
print

m.send_all("WHOIS $c1a")
m.expect(c1a, "Show account in WHOIS", ":.+ 330 $me $c1a client1 :is logged in as")
m.clearlog()
print

