#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send(c3a, "CHGIDENT $c1a newident")
m.expect(c3a, "Should get permission denied if not IRCOp", ":.* 481 $me :Permission Denied.*")
m.clearlog()

m.send_all("WHOIS $c1a")
m.not_expect_all("Should not see new ident in WHOIS", ":.* 311 $me $c1a newident .*")
m.clearlog()
print

m.send(c3a, "OPER netadmin test")
m.send(c3a, "CHGIDENT $c1a newident")
m.clearlog()

m.send_all("WHOIS $c1a")
m.expect_all("Should see new ident in WHOIS", ":.* 311 $me $c1a newident .*")
m.clearlog()
print
