#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c1b = m.new('c1b')
c1c = m.new('c1c')
m.connect()

m.send(c1c, "PRIVMSG $c1b :\001DCC SEND some.forbidden 12345 1024 65535\001")
m.expect(c1b, "Expect DCC to go through", "\001DCC SEND some\.forbidden")
m.clearlog()
print

m.send(c1a, "DCCDENY *.forbidden this is not allowed")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "DCCDENY *.forbidden this is not allowed")
m.expect(c1a, "Added DCCDENY notice", "$c1a added a temporary DCCDENY for \*\.forbidden \(this is not allowed\)")
m.clearlog()
print

m.send(c1c, "PRIVMSG $c1b :\001DCC SEND some.forbidden 12345 1024 65535\001")
m.not_expect(c1b, "DCC should not go through", "\001DCC SEND some\.forbidden")
m.expect(c1c, "Blocked message", ":.+ 531 $me $c1b :Cannot DCC SEND file: this is not allowed")
m.clearlog()
print

m.send(c1a, "UNDCCDENY *.forbidden")
m.expect(c1a, "Removed DCCDENY notice", "$c1a removed a temporary DCCDENY for \*\.forbidden")
m.clearlog()
print

