#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "DNS")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "DNS")
m.expect(c1a, "DNS Statistics (header)", ":.+ 304 $me :DNS CACHE Stats")
m.expect(c1a, "DNS Statistics (hits)", ":.+ 304 $me : hits: [0-9]+")
m.expect(c1a, "DNS Statistics (misses)", ":.+ 304 $me : misses: [0-9]+")
m.clearlog()
print

m.send(c1a, "DNS l")
m.expect(c1a, "DNS Cache list (header)", ":.+ 304 $me :DNS CACHE List")
# should be safe to check for this:
# nope, not anymore: https://github.com/c-ares/c-ares/pull/430
# too bad. now we can't check this anymore.
#m.expect(c1a, "DNS Statistics (hits)", ":.+ 304 $me : localhost \[127\.0\.0\.1\]")
m.clearlog()
print

m.send(c1a, "DNS c")
m.expect(c1a, "DNS Cache clear", ":.+ NOTICE $me :.*DNS cache cleared")
m.clearlog()
print
