#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a)
m.expect(c1a, "user in channel", "JOIN")
print

m.send(c1a, "KILL $c3a :please die")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c2a, "OPER netadmin test")
# Disable syncer since one of the clients is going to die
m.sync = 0
m.send(c1a, "KILL $c3a :please die")
m.expect_all("KILL Notice to opers", ":.+ NOTICE $me :.*Client killed.* $c3a.*\[by: $c1a\] \(please die\)", timeout = 5, skip = c3a)
m.expect(c3a, "Killed client should see KILL notification", ":$c1a.+ KILL $c3a :please die", timeout = 5)
m.expect(c3a, "Killed client should receive ERROR Closing link", "ERROR :Closing Link: $c3a.*\(Killed by $c1a \(please die\)\)", timeout = 5)
m.expect_all("See QUIT in channel", ":$c3a.+ QUIT :Killed by $c1a \(please die\)", timeout = 5, skip = c3a)
print
