#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c1b = m.new('c1b')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send(c1a, "LOCOPS this is a locops test")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1b, "OPER netadmin test")
m.send(c2a, "OPER netadmin test")
m.send(c1a, "LOCOPS this is a locops test")
m.expect(c1a, "Local opers should see locops", ":irc.+ NOTICE $me :from $c1a: this is a locops test")
m.expect(c1b, "Local opers should see locops", ":irc.+ NOTICE $me :from $c1a: this is a locops test")
m.not_expect(c3a, "Non-opers should not see locops", "this is a locops test")
m.not_expect(c2a, "Opers on other servers should not see locops", "this is a locops test")
print
