#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "OPERMOTD")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "OPERMOTD")
m.expect(c1a, "OPERMOTD output 375 (header)", ":.+ 375 $me :- irc.* Message of the Day")
m.expect(c1a, "OPERMOTD output 372 (date)", ":.+ 372 $me :.*IRC Operator Message of the Day")
m.expect(c1a, "OPERMOTD output 372 (text)", ":.+ 372 $me :- This is the oper MOTD")
m.expect(c1a, "OPERMOTD output 372 (text)", ":.+ 372 $me :- last line of OPERMOTD")
m.expect(c1a, "OPERMOTD output 376 (end)", ":.+ 376 $me :End of /OPERMOTD command")
m.clearlog()
print
