#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a, skip = c3a)
m.expect(c1a, "see others joining", ":c2a.*JOIN")
m.clearlog()
print

m.send(c1a, "SAJOIN $c3a " + chan)
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "SAJOIN $c3a " + chan)
m.expect_all("See c3a joining", ":c3a.*JOIN", timeout = 5)
m.expect(c3a, "See that you are forced joined", ":irc.+ NOTICE $me :\*\*\* You were forced to join " + chan)
m.clearlog()
print

# Need to disable the auto-syncer here due to 1 client parting all channels,
# including the auto syncer channel.
m.sync = 0

m.send(c1a, "SAJOIN $c3a 0")
m.expect_all("See c3a leaving", ":c3a.*PART", timeout = 5)
m.expect(c3a, "See that you are forced to part all channels", ":irc.+ NOTICE $me :\*\*\* You were forced to join 0", timeout = 5)
m.clearlog()
print

m.send(c1a, "SAJOIN $c3a @" + chan)
m.expect_all("See c3a joining", ":c3a.*JOIN", timeout = 5)
m.expect_all("See c3a receiving ops", ":.*MODE " + chan + " \+o $c3a", timeout = 5)
m.expect(c3a, "See that you are forced joined", ":irc.+ NOTICE $me :\*\*\* You were forced to join " + chan)
m.clearlog()
print
