#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a)
m.expect(c1a, "see others joining", ":c2a.*JOIN")
m.clearlog()
print

m.send(c1a, "SAPART $c3a " + chan)
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "SAPART $c3a " + chan)
m.expect(c3a, "See that you are forced parted", ":irc.+ NOTICE $me :\*\*\* You were forced to part " + chan)
m.expect_all("See c3a parting", ":c3a.*PART", timeout = 5)
m.clearlog()
print
