#!/usr/bin/python3
import irctestframework.irctest
import time

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a, skip = c3a)
m.expect(c1a, "see others joining", ":c2a.*JOIN")
m.clearlog()
print

m.send(c1a, "TEMPSHUN $c3a please shut up")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.sync = 0
# Disable syncer, since one of the clients can no longer msg.
m.send(c1a, "TEMPSHUN $c3a please shut up")
m.expect(c1a, "Temporary shun added notice", ":irc3.+ NOTICE $c1a :.*Temporary shun added on user $c3a.* \[reason: please shut up\] \[by: $c1a\]", timeout = 5)
m.clearlog()
print

m.send(c3a, "PRIVMSG " + chan + " :this message should not be delivered")
time.sleep(5) # yeah, I don't like it either, but it's necessary..
m.not_expect_all("TEMPSHUNed user should not be able to PRIVMSG (should not error, but no delivery either)", ":$c3a.*PRIVMSG")
m.clearlog()
print
