#!/usr/bin/python3
import irctestframework.irctest
import time

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "TSCTL")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "TSCTL")
m.expect(c1a, "See time on irc1", ":irc1.+ NOTICE $c1a :\*\*\* Server=irc1\.test\.net TStime=[0-9]+")
m.expect(c1a, "See time on irc2", ":irc2.+ NOTICE $c1a :\*\*\* Server=irc2\.test\.net TStime=[0-9]+", timeout=5)
m.expect(c1a, "See time on irc3", ":irc3.+ NOTICE $c1a :\*\*\* Server=irc3\.test\.net TStime=[0-9]+", timeout=5)
m.clearlog()
print
