#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send(c1a, "WALLOPS this is a wallops test")
m.expect(c1a, "Command not permitted as non-ircop", ":.+ 481 $me :Permission Denied")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "WALLOPS this is a wallops test")
m.expect_all("Everyone should see wallops", ":$c1a.* WALLOPS :this is a wallops test", skip=c1a)
print
