#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

# Local user — should match
m.send(c1a, "VHOST crule_is_local test")
m.expect(c1a, "is_local() should match for local user", "Your vhost is now")
m.clearlog()
print
