#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
m.connect()

PASS = "Your vhost is now"
FAIL = "No vHost lines available"

# c1a on irc1 — should match
m.send(c1a, "VHOST crule_match_server test")
m.expect(c1a, "match_server('irc1') should match for c1a on irc1", PASS)
m.clearlog()
print

# c2a on irc2 — should NOT match
m.send(c2a, "VHOST crule_match_server test")
m.expect(c2a, "match_server('irc1') should NOT match for c2a on irc2", FAIL)
m.clearlog()
print
