#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c2a, skip = c3a)
m.expect(c1a, "users in channel", "JOIN")
print

m.send(c2a, "MODE " + chan + " +iV")
m.expect(c1a, "MODE +iV", ":c2a.*MODE.*\+iV")
print

m.send(c1a, "INVITE $c3a " + chan)
m.expect(c1a, "Expect 518 error numeric on /INVITE for non-ops", " 518.*Cannot invite")
print

m.send(c2a, "INVITE $c3a " + chan)
m.expect(c1a, "Expect 518 error numeric on /INVITE for ops too", " 518.*Cannot invite")
print

m.send(c3a, "JOIN " + chan)
m.not_expect(c1a, "User should be unable to join since he was never invited", ":c3a.*JOIN")
print
