#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c2a)
m.expect(c1a, "users in channel", "JOIN")
print

m.send(c2a, "MODE " + chan + " +N")
m.expect(c1a, "MODE +N", ":c2a.*MODE.*\+N")
print

# Need to disable the auto-syncer here due to the nick change
m.sync = 0
m.send(c3a, "NICK zzz")
m.expect(c3a, "Expect 447 error numeric on /NICK", " 447.*not change nickname", timeout = 10)
m.not_expect(c1a, "Should be no NICK event", ":c3a.*NICK")
print
