#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a, skip = c3a)
m.expect(c1a, "first user in channel", ":c1a.*JOIN")
m.expect(c2a, "second user in channel", ":c2a.*JOIN")
print

m.send(c1a, "MODE " + chan + " +O")
m.expect(c1a, "cannot set +O if not IRCOp", "974.*You are not an IRC operator")
m.not_expect(c2a, "no MODE +O if not IRCOp", ":c1a.*MODE.*\+O")
m.clearlog()
print

m.send(c1a, "OPER netadmin test")
m.send(c1a, "MODE " + chan + " +O")
m.expect(c2a, "MODE +O set", ":c1a.*MODE.*\+O")
print

m.send(c3a, "JOIN " + chan)
m.expect(c3a, "unable to join with +O (numeric 520)", "520.*IRCops only")
m.not_expect(c1a, "should not see JOIN for user if +O", ":c3a.*JOIN")
m.clearlog()
print

m.send(c3a, "OPER netadmin test")
m.send(c3a, "JOIN " + chan)
m.not_expect(c3a, "able to join with +O if oper (nonumeric 520)", "520.*IRCops only")
m.expect(c1a, "should see JOIN for user if +O and IRCOp", ":c3a.*JOIN")
print
