#!/usr/bin/python
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.joinall(chan, creator = c2a)
m.expect(c1a, "users in channel", "JOIN")
print

m.send(c2a, "MODE " + chan + " +M")
m.expect(c1a, "MODE +M", ":c2a.*MODE.*\+M")
print

m.send(c1a, "PRIVMSG " + chan + " :hello")
m.expect(c1a, "should show a 404 numeric if not identified, with cmode +M", "404 .*You must have a registered nick")
m.not_expect(c3a, "should block messages if not identified, with cmode +M", ":c1a.*PRIVMSG.*this is red")
print

print 'TODO: test with registered and +M'
