#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "CREDITS")
m.expect(c1a, "CREDITS output", ":.+ 371 $me :.*UnrealIRCd.*redits.*")
m.clearlog()
print
