#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send_all("ISON :$c1a thisnickdoesnotexist $c2a irc1.test.net $c3a")
m.expect_all("ISON response", "$c1a $c2a $c3a")
m.clearlog()
print
