#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a, skip = c3a)
m.expect(c1a, "first user in channel", ":c1a.*JOIN")
m.expect(c2a, "second user in channel", ":c2a.*JOIN")
m.clearlog()
print

m.send(c1a, "MODE " + chan + " +i")
m.expect(c2a, "MODE +i", ":c1a.*MODE.*\+i")
m.clearlog()
print

m.send(c3a, "KNOCK " + chan)
m.expect(c3a, "knocked response", "Knocked on " + chan)
m.expect(c1a, "Knock notice to ops", ".*Knock.*by $c3a.*no reason")
m.not_expect(c2a, "No knock notice to non-ops", ".*Knock.*by") # no ops = no knock noticem
m.clearlog()
print

m.send(c3a, "KNOCK " + chan + " :hi there!")
m.expect(c3a, "knocked response", "Knocked on " + chan)
m.expect(c1a, "Knock notice to ops", ".*Knock.*by $c3a.*hi there")
m.not_expect(c2a, "No knock notice to non-ops", ".*Knock.*by") # no ops = no knock noticem
m.clearlog()
print
