#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "LICENSE")
m.expect(c1a, "LICENSE output", ":.+ 371 $me :.*UnrealIRCd License.*")
m.clearlog()
print
