#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "LINKS")
m.expect(c1a, "Server 2 hops away", ":.+ 364 $me irc3\.test\.net irc2\.test\.net :2 Secondary test")
m.expect(c1a, "Server 1 hop away", ":.+ 364 $me irc2\.test\.net irc1\.test\.net :1 Hub")
m.expect(c1a, "Ourselves", ":.+ 364 $me irc1\.test\.net irc1\.test\.net :0 Primary test server")
m.clearlog()
print
