#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a)
m.expect(c1a, "user in channel", "JOIN")
print

m.send(c1a, "MODE " + chan + " +nt")
m.expect_all("MODE change on channel", ":$c1a.* MODE " + chan)
m.clearlog()
print

m.send(c1a, "TOPIC " + chan + " :this is a nice topic")
m.expect_all("TOPIC change on channel", ":$c1a.* TOPIC " + chan)
m.clearlog()
print

m.send_all("LIST")
m.expect_all("LIST head (numeric 321)", ":.+ 321 $me Channel :Users  Name")
m.expect_all("LIST channel entry (numeric 322)", ":.+ 322 $me " + chan + " [0-9]+ :\[\+nt\] this is a nice topic")
m.expect_all("LIST end (numeric 323)", ":.+ 323 $me :End of /LIST")
m.clearlog()
print
