#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "LUSERS")
m.expect(c1a, "LUSERS output 251 (text)", ":.+ 251 $me :There are .* users and .* invisible on .* servers")
m.expect(c1a, "LUSERS output 255 (text)", ":.+ 255 $me :I have .* clients and .* servers")
m.expect(c1a, "LUSERS output 265 (local counts)", ":.+ 265 $me [0-9]+ [0-9]+ :Current local users .*, max .*")
m.expect(c1a, "LUSERS output 266 (global counts)", ":.+ 266 $me [0-9]+ [0-9]+ :Current global users .*, max .*")
m.clearlog()
print
