#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "MAP")
m.expect(c1a, "IRC1", ":.+ 006 $me :irc1\.test\.net")
m.expect(c1a, "IRC2", ":.+ 006 $me :`-irc2\.test\.net")
m.expect(c1a, "IRC3", ":.+ 006 $me :  `-irc3\.test\.net")
m.clearlog()
print
