#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send(c1a, "MONITOR + $c3a")
m.expect(c1a, "730 numeric for user that is online", ":.+ 730 $me :$c3a!username@Clk.*")
m.clearlog()
print

m.send(c1a, "MONITOR + somenick-m")
m.expect(c1a, "731 numeric for user that is offline", ":.+ 731 $me :somenick-m")
m.clearlog()
print

m.send(c1a, "MONITOR S")
m.expect(c1a, "730 numeric for user that is online", ":.+ 730 $me :$c3a!username@Clk.*")
m.expect(c1a, "731 numeric for user that is offline", ":.+ 731 $me :somenick-m")
m.clearlog()
print

# Need to disable the auto-syncer here due to the nick change
m.sync = 0

# Test nick change
c3a_original_nick = c3a.nick
m.send(c3a, "NICK somenick-m")
m.expect(c1a, "731 numeric for user that went offline (nick change)", ":.+ 731 $me :" + c3a_original_nick, timeout = 10)
m.expect(c1a, "730 numeric for user that got online (nick change)", ":.+ 730 $me :somenick-m!username@Clk-.*", timeout = 10)
m.clearlog()
print

# Test quit
m.send(c3a, "QUIT :poof!")
m.expect(c1a, "731 numeric for user that went offline (quit)", ":.+ 731 $me :somenick-m", timeout = 10)
m.clearlog()
print
