#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "MOTD")
m.expect(c1a, "MOTD output 375 (header)", ":.+ 375 $me :- irc.* Message of the Day")
m.expect(c1a, "MOTD output 372 (date)", ":.+ 372 $me :.*[0-9]+:[0-9]+")
m.expect(c1a, "MOTD output 372 (text)", ":.+ 372 $me :- This is a test server")
m.expect(c1a, "MOTD output 376 (end)", ":.+ 376 $me :End of /MOTD command")
m.clearlog()
print
