#!/usr/bin/python
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a)
m.expect_all("users in channel", "JOIN")
m.send(c1a, "MODE " + chan + " +vv $c1a $c2a")
m.clearlog()
print

m.send_all("NAMES " + chan)
m.expect_all("NAMES should list client 1", ":.* 353 $me = " + chan + " :.*@$c1a")
m.expect_all("NAMES should list client 2", ":.* 353 $me = " + chan + " :.*\+$c2a")
m.expect_all("NAMES should list client 3", ":.* 353 $me = " + chan + " :.*$c3a")
