#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

m.send(c1a, "TIME")
m.expect(c1a, "TIME response", ":.+ 391 $me irc1\.test\.net :.* .* [0-9]+ [0-9]+ .*:.*")
m.clearlog()
print
