#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, creator = c1a)
m.expect(c1a, "user in channel", "JOIN")
print

m.send(c1a, "TOPIC " + chan + " :this is a nice new topic")
m.expect_all("Everyone should see TOPIC change", ":$c1a.* TOPIC " + chan + " :this is a nice new topic")
m.clearlog()
print

m.send_all("TOPIC " + chan)
m.expect_all("After querying for topic, see the topic text via numeric 332", " 332 .* " + chan + " :this is a nice new topic")
m.expect_all("After querying for topic, see the topic setter and time via numeric 333", " 333 .* " + chan + " $c1a!.*@.* [0-9]{10}")
m.clearlog()
print

m.send(c1a, "TOPIC " + chan + " :")
m.expect_all("Everyone should see TOPIC change when set to empty", ":$c1a.* TOPIC " + chan + " :")
m.clearlog()
print

m.send_all("TOPIC " + chan)
m.expect_all("After querying for topic, see the (empty) topic text via numeric 332", " 332 .* " + chan + " :")
m.expect_all("After querying for topic, see the topic setter and time via numeric 333", " 333 .* " + chan + " $c1a!.*@.* [0-9]{10}")
m.clearlog()
print
