#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send(c1a, "WATCH +$c3a")
m.expect(c1a, "604 numeric for user that is online", ":.+ 604 $me $c3a username Clk.* [0-9]+ :is online")
m.clearlog()
print

m.send(c1a, "WATCH +somenick-w")
m.expect(c1a, "605 numeric for user that is offline", ":.+ 605 $me somenick-w \* \* 0 :is offline")
m.clearlog()
print

m.send(c1a, "WATCH L")
m.expect(c1a, "604 numeric for user that is online", ":.+ 604 $me $c3a username Clk.* [0-9]+ :is online")
m.expect(c1a, "605 numeric for user that is offline", ":.+ 605 $me somenick-w \* \* [0-9]+ :is offline")
m.clearlog()
print

# Need to disable the auto-syncer here due to the nick change
m.sync = 0

# Test nick change
c3a_original_nick = c3a.nick
m.send(c3a, "NICK somenick-w")
m.expect(c1a, "601 numeric for user that went offline (nick change)", ":.+ 601 $me " + c3a_original_nick + " username Clk-.* [0-9]+ :logged offline", timeout = 10)
m.expect(c1a, "600 numeric for user that got online (nick change)", ":.+ 600 $me somenick-w username Clk-.* [0-9]+ :logged online", timeout = 10)
m.clearlog()
print

# Test quit
m.send(c3a, "QUIT :poof!")
m.expect(c1a, "601 numeric for user that went offline (quit)", ":.+ 601 $me somenick-w username Clk-.* [0-9]+ :logged offline", timeout = 10)
m.clearlog()
print
