#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.join_all(chan, skip = c3a, creator=c1a)
m.expect(c1a, "users in channel", "JOIN")
m.clearlog()
print

bannedchan = m.randchan()
m.send(c3a, "JOIN " + bannedchan)
m.send(c1a, "MODE " + chan + " +b ~channel:" + bannedchan)
m.expect(c1a, "expect ban to be set", ":.+ MODE " + chan + " \+b")
m.clearlog()
print

m.send(c3a, "JOIN " + chan)
m.expect(c3a, "Client should receive error on JOIN attempt", ":irc.+ 474 $c3a " + chan + " :Cannot join channel \(\+b\)")
m.not_expect_all("Client should NOT be able to join with +b ~channel", ":c3a.* JOIN ")
m.clearlog()
print

m.send(c3a, "PART " + bannedchan)
m.send(c3a, "JOIN " + chan)
m.not_expect(c3a, "Client should NOT receive error on JOIN attempt", ":irc.+ 474 $c3a " + chan + " :Cannot join channel \(\+b\)")
m.expect_all("Client should be able to join now", ":c3a.* JOIN ")
m.clearlog()
print
