#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

m.send(c3a, "MODE $c3a +x")

chan = m.randchan()
m.join_all(chan)
m.expect(c1a, "users in channel", "JOIN")
print

m.send(c1a, "CAP REQ chghost")
m.send(c3a, "MODE $c3a -x")
m.expect(c1a, "with CAP chghost a CHGHOST notification should be generated", ":c3a.* CHGHOST")
m.not_expect(c2a, "without CAP chghost no CHGHOST notification should be generated", ":c3a.* CHGHOST")
print
