#!/bin/bash
if [ "$TIMEOUT" = "" ]; then
	TIMEOUT=25
fi

echo Executing: $1
if [ ! -d logs ]; then
	echo "ERROR: Directory logs/ does not exist"
	exit 1
fi
if [ ! -d logs/failure ]; then
	echo "ERROR: Directory logs/failure does not exist"
	exit 1
fi
if [ ! -d logs/success ]; then
	echo "ERROR: Directory logs/success does not exist"
	exit 1
fi

# strip ./, convert . to _, strip .py, and add .log suffix:
LOGFILE="logs/`echo "$1"|sed 's/\.\///g'|sed 's/\//__/g'|sed 's/\.py//g'`.log"
export PYTHONIOENCODING=utf-8
timeout --kill-after=5 --signal=INT $TIMEOUT $* 1>$LOGFILE 2>&1
if [ "$?" -eq 0 ]; then
	mv $LOGFILE logs/success
else
	mv $LOGFILE logs/failure
fi
