#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
m.connect()

chan = "#permanent_test"
m.join_all(chan, creator=c1a)
m.send_all("MODE " + chan)
m.send_all("MODE " + chan + " b")
m.send_all("MODE " + chan + " e")
m.send_all("MODE " + chan + " I")
m.expect_all("MODE +PT should be set after rejoin", "324.*\+PT")
m.expect_all("ban should be set after rejoin", "367.*ban!")
m.expect_all("exempts should be set after rejoin", "348.*exempt!")
m.expect_all("invexes should be set after rejoin", "346.*invex!")
