#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

chan = m.randchan()
m.send(c1a, "JOIN " + chan)
m.expect(c1a, "user in channel", "JOIN")
print

m.send_all("WHOIS $c1a", skip = c1a)
m.expect_all("Channel should be visible with umode -p", "319.*" + chan, skip = c1a)
print

m.send(c1a, "MODE $c1a +p")
m.expect(c1a, "MODE set", "MODE $c1a :\+p")
m.clearlog()
print

m.send_all("WHOIS $c1a", skip = c1a)
m.not_expect_all("Channel should not be visible with umode +p", "319.*" + chan, skip = c1a)
print

