#!/usr/bin/python3
import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
c1a = m.new('c1a')
c2a = m.new('c2a')
c3a = m.new('c3a')
m.connect()

# Need to disable the auto-syncer here due to the +R
m.sync = 0

m.send(c1a, "MODE $c1a +R")
m.expect(c1a, "MODE set", "MODE $c1a :\+R", timeout = 10)
m.clearlog()
print

m.send_all("PRIVMSG $c1a :test 123", skip = c1a)
m.expect_all("should error on unregistered msg to +R user", "531.*You must identify", skip = c1a, timeout = 15)
m.not_expect(c1a, "No message from unregistered users", "test 123")
m.clearlog()
print

# Syncer can be re-enabled, yay:
m.sync = 1
m.send(c1a, "MODE $c1a -R")
m.expect(c1a, "MODE unset", "MODE $c1a :-R")
m.clearlog()
print

m.send_all("PRIVMSG $c1a :test 456", skip = c1a)
m.expect(c1a, "Message from unregistered users with -R", ":c2a.*test 456")
m.expect(c1a, "Message from unregistered users with -R", ":c3a.*test 456")
m.not_expect_all("should NOT error on unregistered msg to +R user", "531.*You must identify", skip = c1a)
print

